### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by devkdas** [ahopkins/obsidian-team-timezone#1]
hai ,

It is not an issue.
one small quick query

@ahopkins 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code .

Sorry for raising an issue to ask this query.

Looking forward for your reply

Thank you.

**Comment by ahopkins** [comment]
Is this related to the obsidian plugin? Or my recent additions to [Sanic](https://github.com/sanic-org/sanic)? I am assuming the latter, this just seems an odd place to ask the question. I have not yet spend much time on this because I need to get a working client on `sanic-testing` first for HTTP/3. Currently, I have only used browsers and curl.

**Comment by devkdas** [comment]
Hai,

Thank you for replying back @ahopkins 

No,this query is not related to obsidian plugin or any additions to sanic or any of your repositries.

Sorry for raising issue which is not related your repositiries.

This query is related to aioquic repository and i have seen you answered to one of the discussions(https://github.com/aiortc/aioquic/discussions/278)

Could you please confirm were you able to create multiple streams in a single connection using aioquic repositry or 
by using curl.

Looking forward for your reply

Hope you will understand.

Thank you.
@Karthikdasari0423

**Comment by devkdas** [comment]
Hai,

Thank you for replying back @ahopkins

No,this query is not related to obsidian plugin or any additions to sanic
or any of your repositries.

Sorry for raising issue which is not related your repositiries.

This query is related to aioquic repository and i have seen you answered to
one of the discussions(aiortc/aioquic#278)

Could you please confirm were you able to create multiple streams in a
single connection using aioquic repositry or
by using curl.

Looking forward for your reply

Hope you will understand.

Thank you.
@Karthikdasari0423
